D-01239 - Chaperone Signup Cleanup
Holo-Host/chaperone pull request #156
Opened 2021-04-19 22:55 UTC by robbiecarlton

2021-04-19 22:59 UTC, robbiecarlton commented on src/index.ts
> -    const $prompt = $('#modal');
afaict, this doesn't do anything. There's no element with id `modal` in the html, and removing this and all references to it doesn't seem to break anything. Lmk if I'm missing something here.

2021-04-20 21:32 UTC, timotree3 requested changes
Looks good overall. A couple comments on the test

2021-04-20 21:32 UTC, timotree3 commented on tests/unit/test_failure_modes.js
> +      type: "success",
Shouldn't this be `type: "error"`? I'm surprised the test is passing

2021-04-20 21:32 UTC, timotree3 commented on tests/unit/test_failure_modes.js
> +  })
This isn't quite right because if signUp succeeds, the catch will not be hit and the test will pass. You could add a failed boolean variable to fix that.

2021-04-20 22:50 UTC, robbiecarlton commented on tests/unit/test_failure_modes.js
> +      type: "success",
You're right. The test is passing because the chaperone code just checks if the value is `!==true`, anything other than a result of `true` throws the error. And actually this shouldn't be have a type field at all, it should just be the error json

2021-04-20 23:30 UTC, timotree3 approved these changes

2021-04-21 13:25 UTC, merged