Add connection check
Holo-Host/chaperone pull request #168
Opened 2021-05-12 11:48 UTC by JettTech

### Updates:
 - adds ws check on signup and signin
 - handles condition when agent is not anonymous, but has lost connection to envoy
 - adds tests for interrupted signup scenario

2021-05-12 12:24 UTC, zo-el reviewed
Looks like there are a few things that need to be fixed as well as the CI.

Also, you seem to have pushed up an index.html

2021-05-13 10:35 UTC, alastairong commented on src/index.ts
> +        if (this.anonymous === false && !this.appWebsocket) {
@JettTech Stupid question - why is it that `this.appWebsocket` is truthy when the connection to envoy exits, but falsey when it does NOT exit?

2021-05-13 15:33 UTC, JettTech commented on src/index.ts
> +        if (this.anonymous === false && !this.appWebsocket) {
lol. Good call.  This is because I was testing in chaperone hcc mode... and I forgot to restore it to the `websocket()?.readystate === 4` check!  I should probably just a  check for the server mode first anyway and do both checks anyway.  Doing this now.

2021-05-13 21:08 UTC, timotree3 commented on src/index.ts
> +        if (this.anonymous === false && (!this.conn || !hcc_mode_connected)) {
Won't `(!this.conn || !hcc_mode_connected)` always be true since we're always either not connected to envoy or not connected to a conductor?

2021-05-13 22:00 UTC, robbiecarlton requested changes
Some logs to remove plus the logic of that if condition.

I ran the tests locally and they all passed, but then the test runner never exited, and it looks like the tests are running forever on CI, so seems likely those things are related.

2021-05-13 22:14 UTC, JettTech commented on index.html
> +<html>
it's residue from manual testing...  I keep forgetting to remove it and add it to the .gitignore too.

2021-05-13 22:17 UTC, JettTech commented on src/index.ts
> +        if (this.anonymous === false && (!this.conn || !hcc_mode_connected)) {
:joy: Thanks for the oversight. I had tested it manually with one of the conditions, then just added the other without thinking that through fully.  I'll update it to: `if (this.anonymous === false && !(this.conn || hcc_mode_connected)`

2021-05-13 22:48 UTC, JettTech commented on src/index.ts
> +          // NOTE: currently signal subscriptions are only for signed in agents
I was trying to point out that while it's the case now, signal subscription might now always only be for signed-in agents, which was a little different than the above comment.  This will prob be self-evident, if and when we do change it, so I'll remov it for now.

2021-05-14 00:50 UTC, robbiecarlton approved these changes

2021-05-14 00:51 UTC, merged