Implement data translator for response package
Holo-Host/chaperone pull request #70
Opened 2020-11-06 17:33 UTC by mjbrisebois

Replaces handling of irregular response format with a standardized data translation library

- [@holo-host/data-translator](https://www.npmjs.com/package/@holo-host/data-translator)

2020-11-10 22:08 UTC, robbiecarlton approved these changes
One small change, at your discretion. If you want to keep that stuff there I'm not worried about it.

2020-11-10 22:08 UTC, robbiecarlton commented on Makefile
> +	npm uninstall --save @holo-host/data-translator; npm install --save @holo-host/data-translator
do we still need this? Looks like temporary tools for while you were working on the library.

2020-11-10 22:11 UTC, robbiecarlton requested changes
I get the same failing tests as in https://github.com/Holo-Host/chaperone/pull/69

2020-11-10 23:58 UTC, robbiecarlton approved these changes

2020-11-11 16:07 UTC, mjbrisebois commented on Makefile
> +	npm uninstall --save @holo-host/data-translator; npm install --save @holo-host/data-translator
No, these are usable by any dev who clones repos into the same directory (eg. `src` or `projects`) which I think is a pretty standard assumption.  Also, the only time a dev would use this is if they are contributing to both repos at the same time and they can quite easily arrange their directories to work this way.

2020-11-11 16:17 UTC, merged