E2E envoy branch
Holo-Host/chaperone pull request #81
Opened 2021-01-05 22:47 UTC by robbiecarlton

2021-01-13 23:04 UTC, mjbrisebois requested changes
A lot of this work seems like a step in the wrong direction.  Sometimes words have been chosen carefully and they should not be changed willy-nilly.  Perhaps our system architecture needs to be made clearer.

2021-01-13 23:04 UTC, mjbrisebois commented on tests/unit/test_websocket.js
> +			},
Shouldn't be sending this to Chaperone.

2021-01-13 23:04 UTC, mjbrisebois commented on tests/unit/test_websocket.js
> +		return true; // new Package(true);
We want to use the data translator here too because we will eventually add error handling and return error packages.

2021-01-14 06:31 UTC, JettTech commented on tests/mock_envoy.js
> +    server.register("holo/service/confirm", async function ([ response_id, response_signature, service_confirmation ]) {
This is how it's currently implemented in servicelogger.

2021-01-14 06:36 UTC, JettTech commented on tests/mock_envoy.js
> +	const response_verified			= KeyManager.verifyWithPublicKey( resp_msg_bytes, resp_sig_bytes, web_agent_public_key );
This is just a test to verify the signature of the host response hash, which follows the same pattern as the test for the confirmation payload signature verification that had already existed.

2021-01-14 06:39 UTC, JettTech commented on tests/mock_envoy.js
> +	console.log('---------------------> server.servicelog.responses[response_id]', server.servicelog.responses[response_id]);
All 'console.log' messages are purely for debugging efforts while trying to fix the last failing test.  They are only temporary, not meant to be merged.

2021-01-14 06:39 UTC, JettTech commented on tests/mock_envoy.js
> +	console.log('\n---------------------> resp_sig_bytes: ', resp_sig_bytes);
Same...

2021-01-14 06:39 UTC, JettTech commented on tests/mock_envoy.js
> +	console.log('\n---------------------> conf_sig_bytes: ', conf_sig_bytes);
Same...

2021-01-14 06:47 UTC, JettTech commented on README.md
> +> PLEASE NOTE: The `hha_hash` referenced in Chaperone represents the header hash of the app within the holo-hosting-app dht. It is not the DNA hash of the holo-hosting-app (hha).
We do define the `installed_app_id`, and in fact, it is only arg provided for `appInfo()`.

2021-01-14 06:58 UTC, JettTech commented on README.md
> +    "instance_prefix": "uhCkkmrkoAHPVf_eufG7eC5fm6QKrW5pPMoktvG5LOC0SnJ4vV1Uv", /// this should be the hha_hash string
Previously, the value of `instance_prefix` was the hha_hash. We used this value to inform both the instance_id (which, yes, has been replaced with the cell_id), as well as the hha_hash used for testing.  

We do still need the `hha_hash` for our tests. I am in support of maybe renaming this config key to `hha_hash` to better reflect that reality, but we do still need this.

2021-01-14 06:59 UTC, JettTech commented on tests/mock_envoy.js
> +			console.log('\ncalling mock envoy with method : ', method);
All 'console.log' messages are purely for debugging efforts while trying to fix the last failing test. They are only temporary, not meant to be merged.

2021-01-14 07:01 UTC, JettTech commented on tests/mock_envoy.js
> +		};
I didn't update all instances of data translator, as we separate ticket to track that work.  I only updated the areas that needed syncing in order to work.

2021-01-14 07:08 UTC, JettTech commented on tests/integration/test_logic.js
> +	    return new Package({ zomeCall_response, host_response }, null, {
Envoy is now passing the host response back to Chaperone in order for the `response_hash` to be signed and to form the `response_digest`, used in the `confirmation_payload` that will be signed.  Therefore, the Package must return the `host_response` alongside the zomeCall response (ie: 'Hello World').

2021-01-14 07:14 UTC, JettTech commented on tests/integration/test_logic.js
> +		},
This info is apart of the `host_response` that is digested and used to form the `confirmation_payload`, which is signed in Chaperone.  Therefore, Chaperone must now receive this info.

2021-01-14 07:15 UTC, JettTech commented on tests/unit/test_websocket.js
>  		});
Envoy is now passing the host response back to Chaperone in order for the `response_hash` to be signed and to form the `response_digest`, used in the `confirmation_payload`.  Therefore, the Package must return the `host_response` alongside the zomeCall response (ie: 'Hello World').

2021-01-14 07:20 UTC, JettTech commented on tests/unit/test_websocket.js
> +			},
This info is apart of the `host_response` that is digested and used to form the `chaperone_payload`.  The host_reponse also includes the signature of the `response_hash`, which means that we cannot just simply create the digest in holo-envoy and avoid sending the full `host_response` to Chaperone.  Therefore, Chaperone must also receive this info.

2021-01-14 07:24 UTC, JettTech commented on tests/unit/test_websocket.js
>  		});
Same as above.

2021-01-14 07:33 UTC, JettTech commented on tests/mock_envoy.js
> +		throw new Error(' KeyManager.verifyWithPublicKey ERROR : ', error);
Agreed. However, I didn't update all instances of data translator, as we separate ticket to track that work. I only updated the areas that needed syncing in order to work.

2021-01-14 07:41 UTC, JettTech commented
There seems to be a misalignment in understanding about the current servicelogger implementation. I've provided clarification about the current implementation in my responses, but please let me know if you have Qs.  

Also, can you point out what "words" you refer to as having been changed "willy-nilly"?  I did not update things unless I saw the need in the updated architecture.

2021-01-14 08:00 UTC, JettTech commented on tests/unit/test_websocket.js
> +		return true; // new Package(true);
I agree that we ultimately want the hhdt here, which is why I left it as a comment, but right now the hhdt package is not expected. It appears that chaperone is currently only expecting a `true` value to be returned from the wormhole call, so passing the Package made the tests fail. - Since we have a separate ticket to track the hhdt full implementation work, I didn't focus on implementing if not yet needed.

2021-01-14 08:17 UTC, JettTech commented on tests/integration/test_cli.js
> +			    "ssl": client.opts.connection.ssl,
Inside [`index.ts`,](https://github.com/Holo-Host/chaperone/blob/develop/src/index.ts#L652) the key is named 'ssl'.

After another review, I see that both `secure` and `ssl` are referenced across multiple tests.  I support using `secure` if it is more flexible, but request that the key name remains consistent across all its usages in Chaperone.

2021-01-14 08:33 UTC, JettTech commented on tests/integration/test_logic.js
> +		envoy.servicelog.responses[ 0 ] = {
I agree that using an ID more specific to the call would be better. In the past, I thought about using a digest of the call instead; I'll update this accordingly.

2021-01-14 08:50 UTC, JettTech commented on tests/unit/test_mock_envoy.js
>      it("should start server, create client, request, and respond", async () => {
Yes, this is the one. I had just stated that the `holo/service/confirm` event at which this test fails, is also referenced in two tests within `tests/unit/test-websocket` ( 'should complete anonymous zome function call ' and  'should complete anonymous zome function call'), yet both do pass.

I also noted that this test will hang when calling `verifyWithPublicKey` to verify the confirmation signature, but oddly, not when calling that same function to verify the response signature immediately prior.

2021-01-14 12:21 UTC, mjbrisebois commented on README.md
> +> PLEASE NOTE: The `hha_hash` referenced in Chaperone represents the header hash of the app within the holo-hosting-app dht. It is not the DNA hash of the holo-hosting-app (hha).
Right, I was comparing it to the wrong logic.

2021-01-14 12:28 UTC, mjbrisebois commented on README.md
> +    "instance_prefix": "uhCkkmrkoAHPVf_eufG7eC5fm6QKrW5pPMoktvG5LOC0SnJ4vV1Uv", /// this should be the hha_hash string
Yes, we use it for these 4 things in Chaperone

- app info
- sign-up
- key-derivation
- call spec

In each case, it just acts as a version number so perhaps we should change our vocabulary to start calling it App Version rather than HHA ID or hash.  `app_version`

2021-01-14 12:34 UTC, mjbrisebois commented on tests/mock_envoy.js
> +    server.register("holo/service/confirm", async function ([ response_id, response_signature, service_confirmation ]) {
Then that probably means we need to revisit the service logger plan which would explain most of the confusion I have in this PR.

2021-01-14 12:36 UTC, mjbrisebois commented on tests/mock_envoy.js
> +		};
Which ticket are you referring to as the separate ticket?

2021-01-14 12:45 UTC, mjbrisebois commented
> There seems to be a misalignment in understanding about the current servicelogger implementation. I've provided clarification about the current implementation in my responses, but please let me know if you have Qs.

Yes, after reading your responses it is clear that some major changes happened in service logger that I am unaware of.  I can think of several reasons why this new service logger architecture is more complicated while providing less value.  I'll have to chat with whoever knows why these changes were made.

2021-01-15 01:08 UTC, JettTech commented on tests/mock_envoy.js
> +		};
[Implement Data-Translator in Chaperone (Receive from Envoy)](https://www51.v1host.com/Holo/story.mvc/Summary?oidToken=Story:20377)

2021-01-15 21:52 UTC, zo-el reviewed
Initial Comments:
- we either choose ssl or secure and update it everywhere even docs
- add host_response as the metadata.
- I support update instance_prefex to app_version

I'll review it again once the failing tests pass.

2021-01-18 21:24 UTC, JettTech commented
@robbiecarlton - This is ready for your review.  (Since you opened this PR, I cannot formally ping for your review on Github.)

2021-01-18 22:33 UTC, zo-el approved these changes
Looks Good.
- `instance_prefix` do we need to change this var to `instance_id` or `app_id`?
- Need to add a `temporary` tag that points to the cases where we circumvent the wormhole because that will be fixed soon.

**Side Note:** Can we get better or a more general formating for this entire repo? It is very hard to read locally.

2021-01-18 22:33 UTC, zo-el commented on src/index.ts
> +     * @prop {string} agent_id			- `hCAk` encoding of public key
```suggestion
     * @prop {string} agent_id			- `uhCAk` encoding of public key
```

2021-01-18 22:33 UTC, zo-el commented on src/index.ts
> +     * let data = await chaperone.callZomeFunction( "core-apps", "holofuel", "transactions", "list_pending" );
`callZomeFunction()` only takes in 3 strings and a `args`.

2021-01-18 22:33 UTC, zo-el commented on src/index.ts
> +	    throw new Error(`Agend ID should be a string starting with hCAk.  Found '${this.agent_id}' (type ${typeof this.agent_id})`);
```suggestion
	    throw new Error(`Agend ID should be a string starting with uhCAk.  Found '${this.agent_id}' (type ${typeof this.agent_id})`);
```

2021-01-19 20:27 UTC, robbiecarlton reviewed
Approved :shipit:

2021-01-19 20:33 UTC, JettTech commented on src/index.ts
> +		if ( this.mode === Chaperone.HCC) {
:sweat_smile: Oh, how I look forward to our days of linting. I'll update this.

2021-01-19 21:08 UTC, merged