B-03763 - handle signals
Holo-Host/chaperone pull request #86
Opened 2021-02-01 23:50 UTC by robbiecarlton

2021-02-01 23:51 UTC, robbiecarlton commented on bin/chaperone-server
> +const path = require('path');
All the changes in this file are formatting changes, except one which I'll point out in a comment below

2021-02-03 00:43 UTC, robbiecarlton commented on tests/mock_envoy.js
> +  server.event('signal', namespace);
attn @peeech - you will probably have to do something like this and line 116 of this file for Envoy

2021-02-03 18:36 UTC, robbiecarlton commented on bin/chaperone-server
> +const path = require('path');
changes in this file are all formatting.

2021-02-04 14:34 UTC, peeech requested changes

2021-02-04 14:34 UTC, peeech commented on src/index.ts
> +        this.appWebsocket = await AppWebsocket.connect(`ws://localhost:${this.port}`, this.sendSignal.bind(this))
second paramenter of `.connect()` is timeout.

2021-02-04 15:15 UTC, peeech commented on src/index.ts
> +    this.parent_window.sendSignal(signal)
```suggestion
    if (!this.parent_window)
        return;
    this.parent_window.sendSignal(signal)
```

2021-02-04 15:16 UTC, peeech commented on src/index.ts
> +    this.parent_window.sendSignal(signal)
Accounts for a case when parent_window is not set up yet by `COMB.listen()`.

2021-02-04 18:27 UTC, peeech commented on src/index.ts
> +        this.appWebsocket = await AppWebsocket.connect(`ws://localhost:${this.port}`, this.sendSignal.bind(this))
actually not true at all. Sorry.

2021-02-04 19:09 UTC, peeech approved these changes

2021-02-04 19:42 UTC, robbiecarlton commented on src/index.ts
> +        this.appWebsocket = await AppWebsocket.connect(`ws://localhost:${this.port}`, this.sendSignal.bind(this))
It depends on the version of `holochain-conductor-api`. The api changed. The newer version does have timeout as its second param. But we're still on `0.0.1-dev.14`

2021-02-04 23:25 UTC, merged