Customizable login branding
Holo-Host/chaperone pull request #93
Opened 2021-02-08 23:17 UTC by timotree3

Haven't tested this out locally. I'm sure it looks bad if it even works.

2021-02-10 21:10 UTC, timotree3 commented
![image](https://user-images.githubusercontent.com/6473438/107572576-71aa3000-6bba-11eb-8a0b-69bcb5cb7da1.png)


This is ready for review!

2021-02-10 21:24 UTC, timotree3 commented
If you want to test this out, I recommend checking out my EC UI branch holochain/elemental-chat-ui#51

2021-02-11 02:29 UTC, timotree3 commented
Note for reviewer: The reason that the SVGs are not referenced by URL even though they are used many times is that if I put them in the `dist/` folder, they are served with the wrong Content-Type by `chaperone-server` such that they render as text not images.

2021-02-12 07:41 UTC, JettTech requested changes
This looks awesome!  I'm impressed with your attention to the design details :tada:

I found one small edit to make, but otherwise, this looks good. Once this is updated, I say let's ship this!  Let me know if you have any Qs in the meantime. Almost there! :running_man:

2021-02-12 07:41 UTC, JettTech commented on src/static/index.html
> +		}
```suggestion
		if (url_params.has('logo_url')) {
    	  $(".app-logo").attr("src", url_params.get('logo_url'));
		} else {
		  $(".app-logo").hide();
		};
```

2021-02-12 07:41 UTC, JettTech commented on src/static/index.html
> +		}
According to the designs, the logo is optional and should default to no image display. Let's just hide the img tag whenever the logo_url is nullish.

2021-02-12 15:32 UTC, timotree3 commented
Feedback should be addressed. I tested the no logo case locally and it hides as expected.

2021-02-15 14:28 UTC, JettTech approved these changes
Tested and LGTM!

2021-02-15 15:10 UTC, merged