B-03916: add joining code option
Holo-Host/chaperone pull request #94
Opened 2021-02-09 11:04 UTC by JettTech

### Updates: 
- [ ] adds joining code input to sign-up modal
- [ ] provides joining code as membrane_proof when calling holo-envoy sign-up event
- [ ] adds unit test

2021-02-10 22:08 UTC, timotree3 commented on src/index.ts
> +              throw new HoloError("Provided invalid joining code of type (%s) as membrane_proof: %s", joiningCode);
How would this if ever trigger given that we're getting `joiningCode` from an `<input>` value field which is always a string and given that the function parameter type is `string`?

2021-02-10 22:18 UTC, timotree3 commented on src/static/index.html
> +					<a href="https://holo.host/faq-tag/elemental-chat" target="_blank">?</a>
This link destination needs to be configurable just like app name and app logo, right?

2021-02-11 17:04 UTC, zo-el reviewed
Looks good. I do not think there needs to be a link to elemental-chat.

2021-02-11 17:24 UTC, timotree3 commented on src/static/index.html
> +					<a href="https://holo.host/faq-tag/elemental-chat" target="_blank">?</a>
Part of the AC for this ticket is

> The help URL link next to Joining Code input field on Elemental Chat login registration is displayed and takes the user to https://holo.host/faq-tag/elemental-chat/

So we need Elemental Chat to be able to tell Chaperone to display this help link, seems like for a different hosted happ it would be a different link though, which is why this relates to my Chaperone Login Form Customization PR #93

2021-02-12 10:02 UTC, JettTech commented on src/index.ts
> +              throw new HoloError("Provided invalid joining code of type (%s) as membrane_proof: %s", joiningCode);
The input value can accept numbers as well.  This is just a simple filter to prevent unnecessary data from passing onward.  Even though this check *is* pretty general atm, I could also see it increasing in specificity as we standardize the joining code in the future.

2021-02-12 10:03 UTC, JettTech commented on src/static/index.html
> +					<a href="https://holo.host/faq-tag/elemental-chat" target="_blank">?</a>
Good catch Timo. Upon another read of the A/C it does imply that the link would only exist on the Elemental Chat version of the login/signup.  I'll make this udpate.

2021-02-15 15:03 UTC, timotree3 approved these changes
Looks good! Now that this has all of the changes from #93 we should wait to merge that first

2021-02-15 18:08 UTC, robbiecarlton requested changes
Couple of comments, also can you update the changelog?

2021-02-15 18:08 UTC, robbiecarlton commented on src/index.ts
> +              throw new HoloError("Provided invalid joining code of type (%s) as membrane_proof: %s", joiningCode);
> The input value can accept numbers as well

But afaict, even if `isNaN(Number(joiningCode)) === true`, it will still always be true that `typeof joiningCode === "string"`

Unless I'm missing something, I think this check can be omitted.

2021-02-15 22:52 UTC, JettTech commented on src/index.ts
> +              throw new HoloError("Provided invalid joining code of type (%s) as membrane_proof: %s", joiningCode);
You two have convinced me.  I'll remove it. :+1:

2021-02-15 23:46 UTC, JettTech commented on bin/html/index.html
> +		  	$("#joining-info").hide();
I totally agree, but was trying to avoid adding scope and additional repo layers (although in this case, it is pretty small).

2021-02-16 00:19 UTC, zo-el approved these changes
Looks good

2021-02-16 00:30 UTC, robbiecarlton approved these changes

2021-02-16 00:39 UTC, zo-el approved these changes

2021-02-16 00:44 UTC, merged